name: Auto News Parser
on:
  schedule:
    - cron: '0 */3 * * *' # Запуск каждые 3 часа
  workflow_dispatch: # Позволяет запускать вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install feedparser beautifulsoup4
    - name: Run parser
      run: python parser.py
    - name: Commit and Push changes
      run: |
        git config --global user.name "NewsBot"
        git config --global user.email "bot@news.com"
        git add .
        git diff-index --quiet HEAD || git commit -m "Автоматическое обновление новостей"
        git push
