name: Auto News Parser
on:
  schedule:
    - cron: '0 */3 * * *' # Сбор каждые 3 часа
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Запуск на стабильном Node24
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install feedparser beautifulsoup4 requests
    - name: Run parser
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      run: python parser.py
    - name: Commit and Push changes
      run: |
        git config --global user.name "NewsBot"
        git config --global user.email "bot@news.com"
        git add .
        git diff-index --quiet HEAD || git commit -m "ИИ-обновление ленты новостей"
        git push
